// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDummyKeyForWeb',
  //   appId: '1:123456789:web:abcdef123456',
  //   messagingSenderId: '123456789',
  //   projectId: 'wanderly-project',
  //   authDomain: 'wanderly-project.firebaseapp.com',
  //   storageBucket: 'wanderly-project.appspot.com',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7DABC7pF4ZSdDgP6gldSYWPvgKZV6foM',
    appId: '1:55812749573:android:7490817418ca7c4a41df6c',
    messagingSenderId: '55812749573',
    projectId: 'wanderly-project-7335e',
    storageBucket: 'wanderly-project.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDummyKeyForIOS',
  //   appId: '1:123456789:ios:abcdef123456',
  //   messagingSenderId: '55812749573',
  //   projectId: 'wanderly-project',
  //   storageBucket: 'wanderly-project.appspot.com',
  //   iosBundleId: 'com.example.wanderly',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDummyKeyForMacOS',
  //   appId: '1:123456789:macos:abcdef123456',
  //   messagingSenderId: '123456789',
  //   projectId: 'wanderly-project',
  //   storageBucket: 'wanderly-project.appspot.com',
  //   iosBundleId: 'com.example.wanderly',
  // );
}
